.TH DietCLI (1)
.SH SYNOPSIS
dietcli [macro|min|vit] [filepath]
.SH DESCRIPTION
DietCli is a blazingly fast, cross\-platform, command line nutrition
tracker written in C++.
.SH ARGUMENTS
.TP
macro
Analyze macronutrients.
.TP
min
Analyze minerals.
.TP
vit
Analyze vitamins.
.SH Files
.TP
consumed.json
File containing consumed nutrition data.
Looks for it in current directory if custom file is not found or
provided.
.TP
rdi.json
File containing recommended daily intake data.
Must be in same directory as program.
